### ISSUE TITLE
EmbeddedCassandraServerHelper Startup Timeout

### ISSUE THREAD

**Issue by ukjbrown** [jsevellec/cassandra-unit#128]
```
ERROR o.c.u.EmbeddedCassandraServerHelper - Cassandra daemon did not start after MILLISECONDSms. Consider increasing the timeout
```

How would you increase the timeout? The MILLISECONDS constant doesn't even exist, hence why the output contains the word "MILLISECONDS", I'm surprised this works at all.

**Comment by ukjbrown** [comment]
Note I get somewhat random test fails because the embedded server doesn't startup correctly. The startup seems to freeze at the following point;

```
DEBUG org.apache.cassandra.db.Keyspace - Initializing system.sstable_activity
INFO  o.a.cassandra.db.ColumnFamilyStore - Initializing system.sstable_activity
```

The I receive;
```
java.lang.AssertionError: Cassandra daemon did not start within timeout
```

Sometimes this happens, other times it works fine. Clearly I can't commit my tests to our CI server. Is anyone else experiencing anything like this?

I'm using Spring ```@EmbeddedCassandra```

spring-unit-spring version 2.1.3.1

**Comment by jsevellec** [comment]
I've recently received a PR that i've going to integrate about that #127

**Comment by ukjbrown** [comment]
Thanks. I'm not sure if the timeout will actually fix the issue though as I think the actual cause may be something different as I'm surprised I'm hitting the timeout on my machine. When the test works there is zero pause at this stage, but when it fails it sits there for about 5 seconds and fails.

I'm running the tests on a brand new i7 MacBook Pro with little else going on, so if the timeout is too short for me, it will be failing for almost everyone.

**Comment by ukjbrown** [comment]
I've just removed use of ```@EmbeddedCassandra``` and replaced with direct API usage;

```
@BeforeClass
public static void before() throws Exception
{
    EmbeddedCassandraServerHelper.startEmbeddedCassandra(20000L);
    Cluster cluster = new Cluster.Builder().addContactPoints("127.0.0.1").withPort(9142).build();
    Session session = cluster.connect();
    CQLDataLoader cqlDataLoader = new CQLDataLoader(session);
    cqlDataLoader.load(new ClassPathCQLDataSet("cql/schema.sql", true, true, "keyspace"));
}
```

and the problem still occurs, except now it just waits even longer at the same stage;

```
DEBUG o.a.c.d.c.CommitLogSegmentManager - Total active commitlog segment space used is 33554432
```

I ran the test about 6 times in a row, the first 5 times it ran successfully with no pause whatsoever, then the final time the above happened.

**Comment by ukjbrown** [comment]
30 seconds - still no success. I don't think there is any link to the timeout in this case, the server appears to be doing something unexpected.

```
11:31:36.513 [COMMIT-LOG-ALLOCATOR] DEBUG o.a.c.d.c.CommitLogSegmentManager - Total active commitlog segment space used is 33554432
11:31:45.613 [COMMIT-LOG-ALLOCATOR] DEBUG o.a.c.d.c.CommitLogSegmentManager - Total active commitlog segment space used is 33554432
11:32:05.636 [main] ERROR o.c.u.EmbeddedCassandraServerHelper - Cassandra daemon did not start after MILLISECONDSms. Consider increasing the timeout
```

**Comment by ukjbrown** [comment]
The last comment in #110 possibly displays the same symptoms.

**Comment by ukjbrown** [comment]
I'm wondering if there is some sort of race condition in the Cassandra startup as when the startup fails the COMMIT-LOG-ALLOCATOR thread spits out the previously mentioned log entries later in the cycle (after the sstable_activity initialisation). When the startup succeeds, these log messages are much further up the log (almost right at the top). ?

**Comment by sparhomenko** [comment]
@ukjbrown We had a similar problem on our CI server, please try out #132.

@jsevellec Please note that #132 for us does not eliminate the need for #127 - even without the race condition default timeout of 10 seconds is not always enough to initialise Cassandra on slower CI machines.

Also, `MILLISECONDSms` is a typo and is already fixed on master with #130.

**Comment by ukjbrown** [comment]
Thanks @sparhomenko, is there actually a fix for #132 ?

**Comment by sparhomenko** [comment]
@ukjbrown #132 is a PR with a potential fix, you can try it from my branch or wait until @jsevellec merges it to master and try from there.

**Comment by glaucio-melo-movile** [comment]
Hi, 

to solve this issue I had to change io.netty version at cassandra-all deps (it's fully functional here). I have committed this change locally. Also, I've updated cassandra-all to the newest stable release as well as the cassandra driver (and fixed two test cases). Let me know how's your SCM model in order to proceed (I've got a permission denied from cassandra-unit repo)

Cheers,
Glaucio Melo

**Comment by eranmizrahi** [comment]
Hi,

Even with latest version of cassandra unit (3.0.0.1), we still have this problem in our CI.
On the local machines, it seems to work o.k.

Any idea how to solve this problem ?

thanks,
Eran.

**Comment by jsevellec** [comment]
You can increase the timeout : #127

**Comment by eranmizrahi** [comment]
i have increase the timeout with large number, and it worked.
thanks !
